### ISSUE TITLE
Axe engine not returning full results set

### ISSUE THREAD

**Issue by sslawrence521** [esteinborn/docker-aatt#1]
My dev ops team is trying out the axe engine in place of htmlcs. A modified version of the AATT-to-axe code was created which displayed all columns of the returned object, instead of selected ones. The axe engine did not return additional information, even with the absolutePaths and elementRef settings in place. Is there something in our docker configuration that needs to be set to allow the full capabilities of the axe engine?

**Comment by esteinborn** [comment]
I am not sure. I created this for myself as a test of AXE, and havent used it since setting it up. Sorry.
